[package]
name = "rustyEngine"
version = "0.1.1"
authors = ["BlackFire"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyMath = { git = "https://github.com/lunardeath80/rustyMath"}
