[package]
name = "rustyEngine"
version = "0.1.0"
authors = ["pukar"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyMath = { git = "https://github.com/lunardeath80/rustyMath"}
